version: "3.8"
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    image: ${DOCKER_USERNAME}/face_recognition-backend:latest
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://nguyenvan:nguyenvan09@db:5432/attendance
  frontend:
    build: ./frontend/face-recognition
    image: ${DOCKER_USERNAME}/face_recognition-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
