name: CI/CD Pipeline
on:
  push:
    branches: 
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest 
    steps:
      - name: Ckeckout code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push backend 
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/face_recognition-backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/face_recognition-backend:latest
      - name: Build and push frontend 
        run: |
          cd frontend/face-recognition 
          docker build -t ${{ secrets.DOCKER_USERNAME }}/face_recognition-frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/face_recognition-frontend:latest